name: wedding_app
description: Wedding Landing App



publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get:
  google_fonts:
  flutter_map: ^6.1.0
  flutter_svg: ^2.0.9
  latlong2:
  http:
#  mongo_dart:
  platform_device_id: ^1.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

#dart run flutter_native_splash:create
flutter_native_splash:

  #  color: "#ffffff"
  background_image: "assets/images/launch_screen.png"
  #  image: assets/images/logo.png
  android_12:

